import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

export const gunStat = v.object({
  kills: v.optional(v.number()),
  headshots: v.optional(v.number()),
})
export const gunsStats = v.object({
  pistol: gunStat,
  magnum: gunStat,
  carbine: gunStat,
  shotgun: gunStat,
  autoShotgun: gunStat,
  scopedRifle: gunStat,
  handgun: gunStat,
  rifle: gunStat,
  smg: gunStat,
  sniper: gunStat,
  bullpup: gunStat,
})

export const modeStat = v.object({
  kills: v.optional(v.number()),
  deaths: v.optional(v.number()),
  game_plays: v.optional(v.number()),
  game_wins: v.optional(v.number()),
  cop_kills: v.optional(v.number()),
  criminal_kills: v.optional(v.number()),
  assists: v.optional(v.number()),
})

export const modesStats = v.object({
  deathmatch: modeStat,
  gungame: modeStat,
})

export const extraRecordFields = {
  coins: v.optional(v.number()),
  pocket_change: v.optional(v.number()),
  game_wins_temple: v.optional(v.number()),
  game_wins_junction: v.optional(v.number()),
  game_wins_harbor: v.optional(v.number()),
  'game_wins_melon factory v2': v.optional(v.number()),
  game_wins_alleyway: v.optional(v.number()),
  game_wins_derailed: v.optional(v.number()),
  game_wins_riviera: v.optional(v.number()),
  handgun_cost_reduction: v.optional(v.number()),
  game_wins_ruins: v.optional(v.number()),
  'game_wins_atomic v2': v.optional(v.number()),
  game_wins_overgrown: v.optional(v.number()),
  game_wins_sandstorm: v.optional(v.number()),
  handgun_damage_increase: v.optional(v.number()),
  handgun_recoil_reduction: v.optional(v.number()),
  handgun_reload_speed_reduction: v.optional(v.number()),
  magnum_damage_increase: v.optional(v.number()),
  magnum_recoil_reduction: v.optional(v.number()),
  magnum_reload_speed_reduction: v.optional(v.number()),
  magnum_cost_reduction: v.optional(v.number()),
  rifle_damage_increase: v.optional(v.number()),
  rifle_recoil_reduction: v.optional(v.number()),
  rifle_reload_speed_reduction: v.optional(v.number()),
  rifle_cost_reduction: v.optional(v.number()),
  shotgun_damage_increase: v.optional(v.number()),
  shotgun_recoil_reduction: v.optional(v.number()),
  shotgun_reload_speed_reduction: v.optional(v.number()),
  shotgun_cost_reduction: v.optional(v.number()),
  pistol_damage_increase: v.optional(v.number()),
  pistol_recoil_reduction: v.optional(v.number()),
  pistol_reload_speed_reduction: v.optional(v.number()),
  scoped_rifle_damage_increase: v.optional(v.number()),
  scoped_rifle_recoil_reduction: v.optional(v.number()),
  scoped_rifle_cost_reduction: v.optional(v.number()),
  scoped_rifle_reload_speed_reduction: v.optional(v.number()),
  sniper_damage_increase: v.optional(v.number()),
  sniper_reload_speed_reduction: v.optional(v.number()),
  sniper_cost_reduction: v.optional(v.number()),
  carbine_damage_increase: v.optional(v.number()),
  carbine_recoil_reduction: v.optional(v.number()),
  carbine_reload_speed_reduction: v.optional(v.number()),
  carbine_cost_reduction: v.optional(v.number()),
  strength_training: v.optional(v.number()),
  bounty_hunter: v.optional(v.number()),
  game_wins_bazaar: v.optional(v.number()),
  knife_attack_delay: v.optional(v.number()),
  knife_damage_increase: v.optional(v.number()),
  body_armor_cost: v.optional(v.number()),
  game_wins_castle: v.optional(v.number()),
  game_wins_reserve: v.optional(v.number()),
  bullpup_cost_reduction: v.optional(v.number()),
  auto_shotgun_cost_reduction: v.optional(v.number()),
  bullpup_damage_increase: v.optional(v.number()),
  bullpup_recoil_reduction: v.optional(v.number()),
  bullpup_reload_speed_reduction: v.optional(v.number()),
  auto_shotgun_reload_speed_reduction: v.optional(v.number()),
  auto_shotgun_recoil_reduction: v.optional(v.number()),
  auto_shotgun_damage_increase: v.optional(v.number()),
  smg_damage_increase: v.optional(v.number()),
  smg_cost_reduction: v.optional(v.number()),
  fastest_win_gungame: v.optional(v.number()),
  game_wins_atomic: v.optional(v.number()),
  'game_wins_melon factory': v.optional(v.number()),
  smg_recoil_reduction: v.optional(v.number()),
  smg_reload_speed_reduction: v.optional(v.number()),
}

export const recordFields = {
  uuid: v.string(),
  displayname: v.optional(v.string()),
  firstLogin: v.optional(v.number()),
  lastLogin: v.optional(v.number()),
  lastLogout: v.optional(v.number()),
  networkExp: v.optional(v.number()),
  mostRecentGameType: v.optional(v.string()),
  newPackageRank: v.optional(v.string()),
  rank: v.optional(v.string()),

  kills: v.optional(v.number()),
  deaths: v.optional(v.number()),
  game_plays: v.optional(v.number()),
  game_wins: v.optional(v.number()),
  game_wins_carrier: v.optional(v.number()),
  round_wins: v.optional(v.number()),
  shots_fired: v.optional(v.number()),
  headshot_kills: v.optional(v.number()),
  bombs_defused: v.optional(v.number()),
  bombs_planted: v.optional(v.number()),
  criminal_kills: v.optional(v.number()),
  assists: v.optional(v.number()),
  cop_kills: v.optional(v.number()),
  level: v.optional(v.number()),
  score: v.optional(v.number()),
  knife_kills: v.optional(v.number()),
  grenade_kills: v.optional(v.number()),

  guns: gunsStats,
  modes: modesStats,
}

export default defineSchema({
  players: defineTable({
    uuid: v.string(),
    username: v.string(),
    displayname: v.string(),
  })
    .index('by_username', ['username'])
    .index('by_uuid', ['uuid']),

  records: defineTable({
    ...recordFields,
  }).index('by_uuid', ['uuid']),
  extraRecords: defineTable({
    uuid: v.string(),
    ...extraRecordFields,
  }),
})
